# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='budget',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
