# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='bought',
        ),
    ]
